name: Build OpenWrt System image

on:
  workflow_dispatch:
    inputs:
      board:
        description: "Select device board"
        required: false
        default: "s905d"
        type: string
      kernel:
        description: "Select kernel version"
        required: false
        default: "6.1.8"
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libssl-dev git gettext unzip wget curl file

      - name: Clone OpenWrt build repo
        run: |
          git clone https://github.com/ophub/amlogic-s9xxx-openwrt.git build-repo
          cd build-repo

      - name: Run build script
        run: |
          cd build-repo
          ./build.sh ${{ inputs.board }} -k ${{ inputs.kernel }}

      - name: Upload firmware to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_${{ inputs.board }}_${{ inputs.kernel }}
          path: ./build-repo/output/*.img.gz
